name: Terraform Plan and Apply

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual trigger

jobs:
  plan:
    name: Validate and plan changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check current directory
        run: pwd

      - name: Pull the repo changes done on the previous job
        run: |
         pwd
         git pull

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -backend=true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: tf_plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
